### PR TITLE
Catch error

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
My only comment here is that we might want to put in tests specifically for this instead of catching an error. This way other problems we encounter will get surfaced as errors later instead of silently swallowed. 

A snippet like this would be safer:

```
if np.all(wt == 0):
    return None
```

**Comment by esheldon** [comment]
that might be more clear; but note that GMixFatalError is only raised for weights equal zero in all the ngmix code base so it will be functionally the same

**Comment by beckermr** [comment]
I see. We may want to rename that error in ngmix but I guess we missed the boat on that.

**Review by beckermr — APPROVED** [review]

**Comment by esheldon** [comment]
There may be a case uncovered in the future where GMixFatalError will be appropriate.

So the specific check on the weights is certainly better.

**Pull request merged**
