### PR TITLE
use sheared positions for LSST mfrac

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
You need to set the bmask for the expanded star masks using the sheared position too.

**Comment by esheldon** [comment]
I am.  Unsheared positions are not even calculated.

**Comment by esheldon** [comment]
https://github.com/esheldon/metadetect/blob/17ccf950dc39a6d3e54ca11f4537551d68726050/metadetect/lsst/measure.py#L271

**Comment by esheldon** [comment]
the bmasks were always using sheared positions

**Comment by beckermr** [comment]
Wait, so that means my whole thing of the positions having to be consistent was never true here?

**Comment by esheldon** [comment]
the `mfrac` were using the unsheared positions, but trimming was using sheared positions, so there was a mismatch

**Comment by beckermr** [comment]
Ouch. So whatever effect I found in my sims did not happen here. Yikes ok.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
