### PR TITLE
BUG guard against zero sum of weights

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
test failure is in ngmix

**Comment by esheldon** [comment]
seemingly unrelated to this PR

**Comment by beckermr** [comment]
Seems like we should track down this ngmix issue.

**Comment by esheldon** [comment]
tests pass on my local machine

**Comment by beckermr** [comment]
Same versions of everything?

**Comment by esheldon** [comment]
Yeah, I started a new env and ran through the install steps in the CI

**Comment by esheldon** [comment]
ahh, except I had installed the stack first.

If I run through the install steps in CI but don't install the stack then I get the failure.

**Comment by esheldon** [comment]
Appears to be a bug in numba.vectorize

If I write my own loop it works fine

**Comment by esheldon** [comment]
numba is currently pinning numpy to 1.20 due to an issue with vectorize:  https://github.com/numba/numba/issues/7175

but when I installed metadetect from the requirements files it seems to have circumvented this pin and I ended up with 1.22 which won't work

**Comment by esheldon** [comment]
Using `numba>0.54.0` seems to work, as it gets 0.54.1.  For some reason using != got 0.53

**Comment by beckermr** [comment]
> but when I installed the metadetect dependencies from the requirements files it seems to have circumvented this restriction and I ended up with 1.22 which won't work

We need to go and pin numba properly in conda-forge maybe?

**Comment by esheldon** [comment]
do you mean pin numba in the ngmix conda forge?

**Comment by beckermr** [comment]
I mean in the repodata patches.

**Comment by beckermr** [comment]
Current deps on 0.53.0 are: 

```
libgcc-ng >=9.3.0, libstdcxx-ng >=9.3.0, llvmlite >=0.36.0,<0.37.0a0, numpy >=1.16.6,<2.0a0, python >=3.7,<3.8.0a0, python_abi 3.7.* *_cp37m, setuptools
```

We need to add an upper bound if upstream changed the pin.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
