### PR TITLE
ENH interpolation code

### PR DESCRIPTION
**Pull request by beckermr**
This PR has interpolation code we will be using to handle masking in mdet.

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon This one is ready for review!

**Comment by esheldon** [comment]
This is awesome.

Do you plant to call these functions from within the metadetect code or do you plan to have the user apply them before running metadetect?

**Comment by beckermr** [comment]
I think having the options built into metadetect is cleanest since we are not forcing users to track two sets of options on their own. However, the user applying them is nice since they can access the results for inspection etc. 

What do you think?

**Comment by esheldon** [comment]
That's fine.  Maybe we put some examples in the `/examples` directory (and remove that old scrap)

**Review by esheldon — APPROVED** [review]

**Pull request merged**
