### PR TITLE
Sim detect

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by beckermr** [comment]
I might be good to put these modules in an lsst specific submodule. Also we will need to adjust the CI to pull the stack.

**Comment by beckermr** [comment]
This code is used for DES so we need to make sure they imports are not required.

**Comment by esheldon** [comment]
i'm catching ImportError in the test, not sure if that's the best way

**Comment by beckermr** [comment]
Can the package as a whole be imported without the stack?

**Comment by esheldon** [comment]
yes, those modules are not automatically imported in the `__init__.py`

**Comment by beckermr** [comment]
Great! then I think we are good.

**Pull request merged**
